version: '3.8'

services:
  web:
    image: uryy/lab9-q1-web:latest
    build: .
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
