name: Deploy Lab9 to Server

on:
  push:
    branches:
      - Q1 # 仅在 Q1 分支 push 代码时触发

  workflow_dispatch: # 允许手动触发 CI/CD

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t uryy/lab9:v1 --push .

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull uryy/lab9:v1
            docker stop lab9-web || true
            docker rm lab9-web || true
            docker run -d -p 8080:80 --name lab9-web uryy/lab9:v1
